### ISSUE TITLE
Verify kid matches issuer

### ISSUE THREAD

**Issue by jtblin** [koajs/jwt#100]
We pass a function to `secret` so that it can verify the JWT based on the `kid` in the header. The `kid` is something like `<issuer>/<key-id>`. We would also like to verify that the `issuer` in the token is correct to avoid that a compromised private key is used to impersonate another service e.g. doing something like `token.header.kid.startsWith(token.payload.iss + '/')`. Unfortunately we cannot do that ourselves at the moment as only the payload is returned by [jsonwebtoken.verify](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) which is used by this lib, and only the header is passed to the [secret provider](https://github.com/koajs/jwt/blob/master/lib/get-secret.js#L11).

I'm proposing that the provider is called with both the header and the payload as a second argument to avoid a breaking change. If you're OK with that, I'm happy to send a PR for that.

**Comment by jtblin** [comment]
@sdd any thoughts on that? Would you accept a PR with that?

**Comment by sdd** [comment]
Hey, sorry for the slow reply - I've been on holiday :relaxed: 

That sounds perfectly fine to me if there are no breaking changes - feel free to submit a PR, I look forward to reviewing it :-)
