### ISSUE TITLE
Alg field should be checked by the server.

### ISSUE THREAD

**Issue by wicktus** [koajs/jwt#102]
Hello,

Correct me if I'm wrong but I think that the Alg field is not an option that can be fixed in this jwt module, alg is known to the server-side and should be checked before analyzing the token ! 

Auth0 issued a [statement](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/)  saying that not fixing the alg field can introduce a security break :

tl;dr : The fact that the header is not crypted and checked means that anyone can simply fix the alg field he wants : none, SHA512, SHA256 etc. a public key can become a private key etc. 

jsonwebtoken, the library powering koa jwt offers this feature, should be simple to make a fix :). Waiting for your inputs before doing any fix.

**Comment by sdd** [comment]
Hi, 

I've been bitten by the vuln you mentioned before during a pentest, so it's something I'm familiar with :-) All of the options for koa-jwt are also passed to jsonwebtoken. Also, jsonwebtoken whitelists the permitted algs (see here https://github.com/auth0/node-jsonwebtoken/blob/master/verify.js) so unless you configured koa-jwt with options.alg['none'...] then you are ok.

**Comment by sdd** [comment]
Sorry, I meant option.alg = ['none',...];

It's a pain replying by phone keyboard :-)

**Comment by wicktus** [comment]
Oh yes indeed you can fully configure jwonwebtoken, just saw the source code. Thanks. :)

**Comment by sdd** [comment]
No problem 😊
