### ISSUE TITLE
Type definitions don't support JWK

### ISSUE THREAD

**Issue by lev-kuznetsov** [koajs/jwt#109]
Type definitions in types/index.d.ts don't support the documented configuration using jwks. Typical configuration looks like this:

```
import * as jwt from 'koa-jwt'
import * as jwks from 'jwks-rsa'

export default jwt({
  secret: jwks({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: "https://foo.com/.well-known/jwks.json"
  }),
  audience: 'https://foo/',
  issuer: "https://foo.com/",
  algorithms: ['RS256']
})
```

And this code works in js. It's easy enough to have a workaround with the missing audience issuer and algorithms keys but the secret is defined as sting | Buffer

I'll happily submit a PR for the missing keys; but I'm not quite sure what to do with the secret.

**Comment by lev-kuznetsov** [comment]
As a workaround I downgraded to 3.2.0 and use my own types

**Comment by beary** [comment]
You could use @types/koa-jwt because the `types/index.d.ts` is outdated.
https://github.com/koajs/jwt/issues/99#issuecomment-301746056

**Comment by nolazybits** [comment]
hit the same problem...

**Comment by sdd** [comment]
The merged PR from @joshuamanns has fixed the audience, issuer and algorithms defs. @lev-kuznetsov: did you solve the jwks secret with your own types? If so, could you submit a PR?

Thanks

**Comment by lev-kuznetsov** [comment]
See either https://github.com/koajs/jwt/pull/122 or https://github.com/koajs/jwt/pull/123

**Comment by lev-kuznetsov** [comment]
Is it possible to merge one of the solutions to fix this?

**Comment by sdd** [comment]
Fixed in https://github.com/koajs/jwt/commit/f37d5768982b06fddcf907f3edaad4f1866dc5a8
