### ISSUE TITLE
Breaking change in minor version

### ISSUE THREAD

**Issue by soygul** [koajs/jwt#11]
Switching to `ctx.state.user` in a minor version update breaks all of existing code that depends on 0.x branch! It's highly inconvenient and minor version change should be reverted to working state while the changes should be applied to 1.x branch. Koa will probably follow the same pattern as they are holding back a new release for some time.

**Comment by chrisvariety** [comment]
@stiang any thoughts on releasing a new major version w/ `ctx.state` ?

**Comment by soygul** [comment]
koa docs still has some `this.user` references but should be about time: https://github.com/koajs/koa/pull/436

**Comment by stiang** [comment]
Thanks for the reminder, @chrisvariety. Just published v0.2.0 which uses ctx.state. Let me know if you have any issues with it.

**Comment by stiang** [comment]
Actually, I pulled v0.2.0 and published v1.0.0 instead. Since it’s a breaking change I need to bump the version substantially.
