### ISSUE TITLE
I'm really confused, don't know how to sign a token after I searched the readme times

### ISSUE THREAD

**Issue by yalishizhude** [koajs/jwt#110]

**Comment by MicroDroid** [comment]
This library seemingly only checks for JWT and decodes it. You need to use [this](https://github.com/auth0/node-jsonwebtoken) to sign tokens.

**Comment by yalishizhude** [comment]
@MicroDroid thx, I've already used it instead

**Comment by MicroDroid** [comment]
You should close this
