### ISSUE TITLE
[Warning] koa deprecated Support for generators will be removed in v3

### ISSUE THREAD

**Issue by eriknyk** [koajs/jwt#111]
Hi I'm getting the following `warning`

```
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md server/index.js:42:5
```

my example code:

```
...
app.use(jwt({ secret: Token.secret }).unless({ path: [
  /^\/api\/authentication/, 
  /^\/api\/signup.*/,
]}));
...
```

I whish to know howto remove the warning, Docs says that I should to use `async`/`await` version of the middleware, however I didn't found howto make that in the Readme.

Any help will be appreciated.
Best Regards.

**Comment by sdd** [comment]
Hi Erik, for existing projects you will need to upgrade Koa along with all koa modules and all of your custom routes that use generators. I can't speak for what other modules that you are using, but npm install koa-jwt@3 will update koa-jwt to the version that uses an async / await implementation.
