### ISSUE TITLE
typescript define file have not isRevoked option

### ISSUE THREAD

**Issue by gushiaoke** [koajs/jwt#112]
export interface Options {
        secret: string | Buffer;
        key?: string;
        getToken?(opts: jwt.Options): string;
        passthrough?: boolean;
        cookie?: string;
        debug?: boolean;
    }

isRevoked ???

**Comment by yuu2lee4** [comment]
yes,and has no tokenKey option.

**Comment by sdd** [comment]
Feel free to submit a PR to fix it, and I'll merge it.
