### ISSUE TITLE
**WANTED**: pass token.payload to secret function 

### ISSUE THREAD

**Issue by az-esm** [koajs/jwt#113]
The current implementation  allow me to pass different secret to verify the token using `ctx.state.secret`
its also possible to get a function to make it done.

In  current implementation of secret function is called like that `return provider(decoded.header);`
*I want to be able decide on my secret based on payload*

**Proposed Solution:**
`return provider(decoded.header, decoded.payload);`
it's will not affect the current existing code and look like safe to add it

update
actually have pending pull request to https://github.com/koajs/jwt/pulls

**Comment by sdd** [comment]
Fixed in https://github.com/koajs/jwt/pull/114. Released as 3.3.0.
