### ISSUE TITLE
Support an option to validate the decoded jwt

### ISSUE THREAD

**Issue by doshisid** [koajs/jwt#117]
Once I have verified the jwt, I want to check if a certain field is set properly.

For eg:
If I have set a `role` field in jwt, on admin routes I want to only allow to pass if the role is set to `admin`.

```
role => jwt({
  secret: confirm.secret,
  validate: decoded => decoded.role === role
})
```

**Comment by sdd** [comment]
This can be very easily done with a downstream middleware. The use case that you provide is more  authorization than authentication, which would normally be handled by a other middleware after koa-jwt.

A rough example, using koa-router:

```javascript
koa.use(jwt({ secret });

const adminOnly = (ctx, next) => ctx.state.user.role === "admin" ? next() : ctx.throw(403);

router.get('/admin', adminOnly, adminRoute);

```

**Comment by doshisid** [comment]
I agree with you. Validations/ Authorizations are better placed in the next middleware.
