### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by joshuamanns** [koajs/jwt#119]
Is this module actively maintained?

**Comment by sdd** [comment]
Hi Josh, yes it is - but I've been a bit lax recently, due to other commitments. I'll make a point of going through the PRs and issues over today and the next few days - was there anything in particular that you are wanting to get merged as a priority?

**Comment by joshuamanns** [comment]
@sdd thanks for the follow up! Yes, in particular there seems to be some type definitions for jwt options that aren’t defined. I submitted a PR that includes a few but maybe it is worth expanding for 100% coverage. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sdd** [comment]
Thanks for the PR, and the nudge regarding maintenance :-)
