### ISSUE TITLE
Make authentication errors available when using passthrough

### ISSUE THREAD

**Issue by dancrumb** [koajs/jwt#124]
Some very useful debugging information is available when JWT authentication fails. However, if `passthrough` is being used, this information is made unavailable. As a result, it cannot even be logged.

I'd love to see that info be made available somehow.

**Comment by sdd** [comment]
Any proposals? maybe a string option `authErrorKey`, which if present and `options.passthrough = true`, `ctx.state[options.authErrorKey]` gets set to the authentication error?

**Comment by dancrumb** [comment]
That's a good option. Alternatively an `onError` handled that is passed the error and the context

**Comment by sjmcdowall** [comment]
We could combine them .. make it authError (optional) -- if it's a String type, make it a state key.. if it's a function invoke as indicated.. ??

**Comment by dancrumb** [comment]
Thinking about it further, I think the key might not be the best approach.

My personal use case is to have two instances of this back to back in my middleware pipeline. Being able to figure out why each piece of middleware failed would be useful, even if it's as simple as just logging out why each failed.

I think the `onError` version would make the state key approach easy to implement for users.

**Comment by sdd** [comment]
An `onError` handler does not really fit in with Koa's middleware style, IMHO.

By using the state key, a downstream middleware could do whatever you like on an auth error:

```javascript
app.use(jwt({ authErrorKey: 'authError' }));

app.use((ctx, next) => {
    const { authError } } = ctx.state;
    
     if (authError) {
    
        // logging: (other loggers are also available)
        console.log(`Auth Error: ${authError}`);

        // 500 response:
        ctx.status = 500;
        ctx.body = { error: authError };
    } else {
        next();
    }
});
```

**Comment by sjmcdowall** [comment]
I have to admit -- that looks pretty clean!

**Comment by dancrumb** [comment]
I went ahead and created an`onError` implementation, but feel free to reject it.

**Comment by dancrumb** [comment]
Again, the problem with using an `authError` key is that it means that you can't have multiple JWT middlewares in your pipeline unless you give each one a different `authError` key... the example becomes a little less clean then.

**Comment by slessans** [comment]
Is there any chance there will be a PR for this? this functionality would be very nice
