### ISSUE TITLE
TypeScript typings (and documentation) wrong for getToken function

### ISSUE THREAD

**Issue by selfinterest** [koajs/jwt#126]
The typings for Options indicate that getToken's first parameter should be the options for the middleware. The documentation says that getToken's first parameter should be the options for the middleware and that "this" inside the function should be the Koa context.

In the code itself, the first parameter to getOptions is (very sensibly) the Koa context, while the options are the second parameter.

To get around this, I used a hack like this:

```typescript
// "get" below is lodash's get method.
const koaJwtOptions = {
    secret: config.secret,
    getToken(opts: any) {   // opts is ACTUALLY Koa.Context
        const jwt = get(opts, "query._j") || get(opts, "query.jwt")
        return jwt;
    }
  }
```

**Comment by sdd** [comment]
Hi @selfinterest - this should be fixed now, as of v3.4.0. See https://github.com/koajs/jwt/blob/master/types/index.d.ts#L17

Thanks!
