### ISSUE TITLE
Update version and publish to npm to fix vulnerability.

### ISSUE THREAD

**Issue by Khromushkin** [koajs/jwt#127]
Thank you for merging https://github.com/koajs/jwt/pull/116. 

But could you please do npm version patch && npm publish ? =) 
It will help a lot. Because now 3.3.1 which is published to npm is still "vulnerable".

**Comment by Lanfei** [comment]
I have the same situation, can you publish it to npm please?

**Comment by sdd** [comment]
Big apologies for the delay - I've published as 3.3.2.

**Comment by Khromushkin** [comment]
Thank you! It was not actually a vulnerability but github show me an annoying alert.
