### ISSUE TITLE
EINVAL thrown inside middleware; why? What do I need to fix?

### ISSUE THREAD

**Issue by tlycken** [koajs/jwt#128]
Using the following middleware declaration,

```
jwt({
  secret: koaJwtSecret({
    jwksUri: options.jwksUri,
    cacheMaxAge: '24h',
    strictSsl: false
  }),
  debug: true,
  getToken: ctx => {
    ctx.state.token = parseBearerTokenHeader(ctx.get('authorization')) || ctx.cookies.get('auth-access-token')
    return ctx.state.token
  }
}).unless({ path: [/^\/auth/] })
```
I'm seeing the errors listed below, and authentication fails. This error message gives me no clue whatsoever on what is wrong - what network request is it trying to make, and why?

```
{ UnauthorizedError: tunneling socket could not be established, cause=connect EINVAL 0.0.16.44:80 - Local (0.0.0.0:0)
    at Object.throw (/app/node_modules/koa/lib/context.js:93:11)
    at jwt (/app/node_modules/koa-jwt/lib/index.js:53:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'tunneling socket could not be established, cause=connect EINVAL 0.0.16.44:80 - Local (0.0.0.0:0)',
  originalError: { Error: tunneling socket could not be established, cause=connect EINVAL 0.0.16.44:80 - Local (0.0.0.0:0)
    at ClientRequest.onError (/app/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' } }
```

**Comment by tlycken** [comment]
Also of possible importance: This only happens in our server environment, not locally. Because of that (and because of the "tunneling" in the error message, I'm suspecting it has something to do with running HTTPS there and HTTP locally, but I have no idea what... 🤔

**Comment by tlycken** [comment]
After some more investigation, it seems the problem here was that I had a `HTTP_PROXY` defined which did not support the requests in question. I'm still not sure what requests this library was making, as adding a `NO_PROXY` for the JWKS host did not help, so I'll keep looking into that, but at least I'm not blocked by this anymore.

**Comment by sjmcdowall** [comment]
@tlycken -- I think you can close this -- the code in JWT doesn't do any network access ever so it's unlikely it's to be at fault...

**Comment by tlycken** [comment]
@sjmcdowall If that's OK, I'd rather keep it open until we have at least figured out what JWT is doing when the network access happens, as that will give me the clue as to where to look (and/or file an issue) next.

**Comment by sdd** [comment]
The network request mentioned is being performed by https://github.com/auth0/node-jwks-rsa, rather than koa-jwt.

As @sjmcdowall says, this is not a koa-jwt error, but most likely a misconfiguration of your network configuration.
