### ISSUE TITLE
Upgrade jsonwebtoken to 8.1.0

### ISSUE THREAD

**Issue by jimmylin212** [koajs/jwt#130]
Hi,

Do you have any plan to upgrade the dependency `jsonwebtoken` to 8.1.0?

I got an 

```
Error.captureStackTrace is not a function
JsonWebTokenError@http://mysite.com
```
when I test on Firefox or other browsers. It seems a fixed [issue](https://github.com/auth0/node-jsonwebtoken/issues/402) on `jsonwebtoken`, and the PR is merged in v8.1.0. 

Or do you have any suggestion that how can I fix this issue? Can I just upgrade to v8.1.0?

Thank you.

**Comment by recidive** [comment]
There's this warning showing up in `yarn`:

`warning koa-jwt > jsonwebtoken > lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.`

I believe newer versions of `jsonwebtoken` has this fixed.

**Comment by sjmcdowall** [comment]
So there are 6 PR's outstanding -- most look good.  Why aren't they merged? What's the process? Who owns this repo??

**Comment by crobinson42** [comment]
+1 bump @sdd

**Comment by crobinson42** [comment]
The latest is 8.3.0 https://github.com/auth0/node-jsonwebtoken/blob/v8.3.0/CHANGELOG.md

**Comment by sdd** [comment]
Sorry for the radio silence - I've been busy with other projects. Right, let's whip this project back into shape.
