### ISSUE TITLE
AUDIENCE is not supported per spec

### ISSUE THREAD

**Issue by nhhockeyplayer** [koajs/jwt#142]
Having configured this library it works

but it stops all routes

audience is suppose to be an array not a string

how can I permit anonymous site visitors to look at home page contact page demo page

everything is being blocked

currently it only takes one string

and I have a list of endpoints that need to be secured and a list of endpoints that need to pass thru freely without being secured

is there a workaround

there is no means to allow anonymous access

**Comment by sjmcdowall** [comment]
You are correct it isn't supported per spec, but that is just an error in the types/index.d.ts file.  Are you writing TS?  If not, it appears you can still just pass an array in the options for audience and it passes it to jsonwebtoken which DOES accept an array or string.   I.e. it should work fine, although it will raise a TS error ...

**Comment by sjmcdowall** [comment]
BTW -- I just submitted a PR #143 to fix the audience index.d.ts definition.

**Comment by nhhockeyplayer** [comment]
thanks friend, how do I get past typescript error

**Comment by nhhockeyplayer** [comment]
thanks friend,

i would like to unit test this

how soon can I get the next rev

**Comment by sjmcdowall** [comment]
You can try my fork .. at least for testing ..

Getting into official master .. is anyone’s guess .. but if you can confirm first with a unit test .. my bad .. that will help!

**Comment by nhhockeyplayer** [comment]
works nice
I instrumented the types file beneath node_modules
thanks so much

**Comment by nhhockeyplayer** [comment]
hello... its been a few months

this was patched

works good

but its never made it into the library manager for NPM

I have to manually edit the file everytime I npm install

can someone check for this

**Comment by raman-nbg** [comment]
I think this can be closed

**Comment by nhhockeyplayer** [comment]
ok closed
