### ISSUE TITLE
"Secret not provided" even if it's configured

### ISSUE THREAD

**Issue by mkgn** [koajs/jwt#146]
I am using Koa 2.7 and koa-jwt 3.5 library. I went through the docs and setup the jwt to work as below.

secret set to "123"

Middlewear configuration is as below;

    app.use(async (ctx, next) => {
		return next().catch((err) => {
                       //error logic
		});
	})
  	.use(jwt({"123"}).unless({
		path: ["/", /\/public/]
	}))
	.use(helmet())	
	.use(bodyParser())
	.use(router.routes());

2) In my login function I use jsonwebtoken libary to encrypt

       var token = jwt.sign(payload, "123"); //secret key is 123
		response.status=200;
		response.set('Authorization', 'Bearer ' + token)

This works fine and I get the token in header. However when trying to call a protected API by passing the token in header; it says "Secret not provided". If the header is properly set, I assume the decrypting is automatically handled by koa-jwt? May be my order of middleware should change?

What am I doing wrong?

**Comment by mkgn** [comment]
Jeez! This was my bad. I think I was drunk... sorry :) It works perfectly!

**Comment by lingxiao-Zhu** [comment]
l meet this problem too,  how to reslove?

**Comment by sjmcdowall** [comment]
More (much more) information is needed.. so far all have been errors on the users side. 

What is the code?

**Comment by ayiooo** [comment]
I meet the same problem how you fix that
