### ISSUE TITLE
Could we get an example of setting opts

### ISSUE THREAD

**Issue by jrgleason** [koajs/jwt#152]
I am trying to set up the opts and I am not sure what this means. Granted I am pretty new to Koa but a quick search doesn't find anything there either. Could we add an opts (specifically a cookie) example to the docs?

**Comment by jrgleason** [comment]
Is is `jwt({cookie:"Authorization"})` rt?

**Comment by sdd** [comment]
The above would work if the cookie name for your auth cookie is `Authorization`.
