### ISSUE TITLE
Add option to enable setting custom JSON object of decoded token in ctx

### ISSUE THREAD

**Issue by Glenny-Codifly** [koajs/jwt#168]
Right now the only paramater that can be changed is the ctx key through the option `key`.
It would be nice to be able to provide a function as an option to allow custom setting of the decoded token in ctx. For example if the token content is deeply nested and you would prefer a flat structure.

**Comment by eufelipemateus** [comment]
i am same problem here.

**Comment by sdd** [comment]
You can do this pretty trivially by adding a 1-line follow-on piece of middleware.

```javascript
app.use(koaJwt(config));
app.use((ctx, next) => { ctx.state.user = yourDecodedTokenFlatteningFunction(ctx.state.user); return next(); });
```

**Comment by Glenny-Codifly** [comment]
Thank you for this workaround, didn't cross my mind at all.
