### ISSUE TITLE
Missing other Claims in decoded JWT

### ISSUE THREAD

**Issue by alexpartsch** [koajs/jwt#188]
In `ctx.state.jwt` i only receive the claims `iss, sub, aud, iat, exp` but not any custom claims, which are present in the token sent to the API (e.g. `username`). Do I need to pass a special option to `jwt({...})` for that? Can't figure this out from the docs.

**Comment by sdd** [comment]
`koa-jwt` defers decoding of the token to the `jsonwebtoken` library by calling [jsonwebtoken.verify](https://www.npmjs.com/package/jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback). The result of this is not modified by `koa-jwt` before it is assigned to `ctx.state.jwt`.

Any options passed to `koa-jwt` when it is instantiated are also passed through to `jsonwebtoken.verify`. I suggest writing a test script that simply passes an example JWT for which you are experiencing this problem to `jsonwebtoken.verify` or `jsonwebtoken.decode` to see what you get from there?
