### ISSUE TITLE
Pass token on query string / allow passing custom getToken function

### ISSUE THREAD

**Issue by techniq** [koajs/jwt#30]
It would be nice to allow passing the token on the query string (`?token=....`) instead of having to passing it as a request header.  [express-jwt](https://github.com/auth0/express-jwt) permits this by allowing you to pass a custom getToken function like so:

```js
app.use(jwt({
  secret: 'hello world !',
  credentialsRequired: false,
  getToken: function fromHeaderOrQuerystring (req) {
    if (req.headers.authorization && req.headers.authorization.split(' ')[0] === 'Bearer') {
        return req.headers.authorization.split(' ')[1];
    } else if (req.query && req.query.token) {
      return req.query.token;
    }
    return null;
  }
}));
```

**Comment by sc0ttyd** [comment]
PR 28 (https://github.com/stiang/koa-jwt/pull/28) seems to be addressing this also.

**Comment by stiang** [comment]
I agree that this would be nice. As I just said in a comment on the existing PR: Any chance of a getToken PR with tests? Will merge :)

**Comment by danwkennedy** [comment]
Is this still in the works? I submitted a PR but haven't gotten feedback yet ¯\_(ツ)_/¯

**Comment by stiang** [comment]
@danwkennedy Sorry about that, will try to get it merged in the next couple of days! Thanks for the PR :)

**Comment by nfantone** [comment]
+1 on this. I'm also waiting for this to be merged.

**Comment by stiang** [comment]
Thanks for the reminder, @nfantone :) I‘ve merged it and published 1.2.0.

Thanks for the contribution, @danwkennedy!

**Comment by nfantone** [comment]
Thanks to you, @stiang!

**Comment by nfantone** [comment]
Now that I'm paying attention to the actual implementation, would it be nice(r) if the `getToken` function didn't replace the entire plugin functionality? Instead, we could be using that as an _alternative_ method for fetching the token.

Let's say I wanted to get the JWT from a query string (which was the initial intent of the PR), but I'd also like to default to `Authorization` header if not found. For that to be possible, I'd have to write code that checks the query string, _but also duplicate the bit about the header_ which is already present in **koa-jwt** (including format validation).

So instead of this,

```javascript
  if (opts.getToken) {
      token = opts.getToken.call(this);
    } else if (opts.cookie && this.cookies.get(opts.cookie)) {
      // ...
 }
```

with chained `else if`s, maybe change it to something like this?

```javascript
  if (opts.getToken) {  
   token = opts.getToken.call(this);
  }

if (!token) {
  if (opts.cookie && this.cookies.get(opts.cookie)) {
      // ...
   }
}
```

That way, if `getFunction` failed to acquire the token, the other implemented methods would kick in. Of course, we would have to document the fact that some mechanisms are always checked by default.

**Comment by nfantone** [comment]
@danwkennedy and @stiang Thoughts ^?

**Comment by danwkennedy** [comment]
Would you think it'd be useful to make the getToken option accept an array of functions with the first non-null value being the winner?

**Comment by nfantone** [comment]
@danwkennedy How would an array of functions help here, exactly?

Are you thinking of something along the lines of:

```javascript
function getTokenFromCookie() { /* ... */ };
function getTokenFromHeader() { /* ... */ };
function getTokenFromParam() { /* ... */ };
var getTokenFns = [getTokenFromCookie, getTokenFromHeader, getTokenFromParam];

app.use(jwt({
  secret: 'hello world !',
  credentialsRequired: false,
  getToken: getTokenFns
}));
```

If so, I'm not entirely sold on it. This is adding extra complexity for something rather simple. But it may be just my impression.

**Comment by nfantone** [comment]
It _might_ be useful if `getToken` would accept that array _as well as_ the function form.

**Comment by danwkennedy** [comment]
@nfantone I would probably do that internally no matter what. The question is whether that functionality should be available to users. I too was thinking the array | function option would be the way to go. However I'm worried the array could potentially impact performance. If we're ok raising that as a concern in the docs and letting users hang themselves if they want, that's a possibility.

**Comment by danwkennedy** [comment]
@nfantone I have an initial implementation for that here:
https://github.com/danwkennedy/jwt/commit/ba4121d090bf2b35bd8791e2e6c1c76813bf06f5

That will just make everything fall through until a token is returned or else an error is thrown. The getToken option just gets unshifted on the list of resolvers so it runs first.

**Comment by nfantone** [comment]
@danwkennedy I like it! Up por for a new PR? Let's have @stiang review it.

**Comment by danwkennedy** [comment]
👍 I'll write up some documentation on that functionality.

What about making the getToken option accept an array or a function?

**Comment by nfantone** [comment]
That would be nice... but a feature not sure it would have much usage. Either way, it won't hurt if it's there.

**Comment by danwkennedy** [comment]
I'm gonna leave it. You could do something similar inside of the getToken function (i.e. check this or check that)

**Comment by danwkennedy** [comment]
https://github.com/koajs/jwt/pull/39 is created
@nfantone, @stiang
