### ISSUE TITLE
Missing callback function parameter

### ISSUE THREAD

**Issue by kimkaid** [koajs/jwt#33]
Is it normal that the JWT.verify function is called without the callback function parameter?

```js
yield JWT.verify(token, secret, opts)
```

Yet, in jsonwebtoken module, it is :

```js
JWT.verify = function(jwtString, secretOrPublicKey, options, callback)
```

jsonwebtoken module tests if the third parameter is a function or not, and if so, take the third parameter as the callback function but what if I want both opts and callback?

**Comment by stiang** [comment]
Yes, when using the `yield` keyword, there is no callback. The main point of the callback in traditional JS programming is to access the result of an async function, but when using generators the function _returns_ the result, so your first line would be something like:

```js
var result = yield JWT.verify(token, secret, opts)
```

Here, the `result` variable will contain the result of the async function call. This is one of the main benefits of using generators - you get to do async JS programming without callbacks.
