### ISSUE TITLE
NPM needs updating

### ISSUE THREAD

**Issue by rrglomsk** [koajs/jwt#49]
Hi! I installed koa-jwt via npm, and was running into issues trying to use the changes outlined in this PR: https://github.com/koajs/jwt/pull/39

I noticed it was included in the 1.2.0 tag here on github, but the latest install (1.2.0) from npm has an older version which does not include these changes. 
I see it was stated NPM was updated (https://github.com/koajs/jwt/pull/39#issuecomment-216288691), but it doesn't seem to be that way heh :)

**Comment by nmec** [comment]
As a workaround, you can use this in your package.json

```
"koa-jwt": "github:koajs/jwt#v1.2.0"
```

**Comment by sc0ttyd** [comment]
v1.3.0 has now been published.
