### ISSUE TITLE
Validating token using audience, issuer never fails

### ISSUE THREAD

**Issue by daghb** [koajs/jwt#51]
Validating claims within audience and issuer fields never fail.

Validating

`app.use(jwt(
{ secret: 'shared-secret', audience: 'http://myapi/protected', issuer: 'http://issuer' }));`

against a token containing

`{ ... audience: 'something-nice', issuer: 'bogus' ... }`

does not fail.

**Comment by sc0ttyd** [comment]
Is this the same issue as https://github.com/auth0/node-jsonwebtoken/issues/53? have you tried using `aud` instead of `audience`?

**Comment by sc0ttyd** [comment]
This works if you use `audience` and `issuer` in koa-jwt's config, and `aud` and `iss` in the JWT itself. See here: https://gist.github.com/sc0ttyd/770ef797913ca34775fbaa41ae8a2acd

Closing issue.
