### ISSUE TITLE
koa@2, ctx.state.user gets undefined value

### ISSUE THREAD

**Issue by clthck** [koajs/jwt#63]
I'm using koa-jwt for koa@2, so I installed koa-jwt by running `npm i --save koa-jwt@koa2`.
Authorizing token works, but when I call `ctx.state.user`, it returns `undefined`. I did some debugging and it turns out that [this line](https://github.com/koajs/jwt/blob/koa-v2/lib/index.js#L41) is executed after route handler function is called. Any idea how to fix this?

**Comment by clthck** [comment]
I found out that this issue occurs when I use koa-jwt with router (`koa-router`). I moved to `app.use()` instead of `router.use()` and it worked as expected.

**Comment by chovy** [comment]
I get a defined value but it doesn't have the user object. just this:

```
{ iat: 1487357347, role: 'user' }
```

**Comment by clthck** [comment]
@chovy not sure what you're talking about. can you elaborate?

**Comment by chovy** [comment]
I need to get a user object from the token. Is there a way to do that?

**Comment by clthck** [comment]
while it's clearly possible to put user object into the token, I think it's better to put single value only (e.g. user id), and then once you decipher payload, get user id back and retrieve whole user record from database with that user id. hope that makes sense for you.

**Comment by chovy** [comment]
I got it working with just `user._id` that's all i really need to restrict access to only objects they created.
