### ISSUE TITLE
installation infomation in the readme.

### ISSUE THREAD

**Issue by classLfz** [koajs/jwt#86]
there is my question:

I want to user `koa-jwt` to help me to build the verification system with koa@1.x, so I am installed link this:
```sh
npm install koa-jwt --save
```
And I run the example like readme, but it doesn't work. I get confused. Later, I realize that is the compatibility between koa-jwt@2.x and koa@1.x. 

```sh
npm install koa-jwt@1 --save
```
It worked! :)

So, I thought write the installation information in the readme will be good.

**Comment by sdd** [comment]
Fixed in https://github.com/koajs/jwt/pull/87
