### ISSUE TITLE
An error accur when import koa-jwt

### ISSUE THREAD

**Issue by jcindex** [koajs/jwt#91]
```javascript
const middleware = async function jwt(ctx, next) {
```
The code above throws a SyntaxError: Unexpected token function, why?

**Comment by sdd** [comment]
Which node version is this with?

**Comment by sdd** [comment]
This can occur if you are using `koa-jwt` version 3.x with node <7.6.  If you are using node < 7.6 with `koa` version 2.x , then you need to use `koa-jwt` version 2.x.

Does this help?

**Comment by sdd** [comment]
Closing due to no response. If you have any further queries @jcindex feel free to ask.
