### ISSUE TITLE
The types directory hasn't been published to npm

### ISSUE THREAD

**Issue by beary** [koajs/jwt#99]
The `types` directory hasn't been published to npm. So after `npm install koa-jwt@3.2.1 --save`, there are no types on node_modules/koa-jwt.

**Comment by jtblin** [comment]
Oh and I actually sent a PR to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa-jwt/index.d.ts) so the types in this repo are outdated.
